name: Run Tests

on:
  push:
    branches:
      - "**" # Trigger on push to any branch
  pull_request:
    branches:
      - main # Trigger on pull request targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test

      - name: Run e2e tests
        run: npm run cypress:run 
        env:
          CI: true # Ensures tests run in Continuous Integration mode

